apiVersion: v1
kind: Service
metadata: 
  name: katmandu-phpinfo-svc
spec:
  ports:
    - 
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: santander-phpinfo-service # tambien se puede poner  {app: santander-phpinfo-service}
    
